### ISSUE TITLE
vs2017怎么编译 variant nnue pytroch

### ISSUE THREAD

**Issue by shuangqiao999** [ianfab/variant-nnue-pytorch#11]
我用vs2017编译 cmakelist.txt 总是报错是怎么回事？

**Comment by ianfab** [comment]
Without an error message it is hard to comment on that. If you are on discord, let's discuss it there. If not, please create a discussion at https://github.com/ianfab/variant-nnue-pytorch/discussions where Chinese users trying to train Xiangqi NNUE can then report their issues and discuss their progress. Alongside this discussion we can then hopefully together improve and complete the guide in https://github.com/ianfab/variant-nnue-pytorch/wiki/%E4%B8%AD%E6%96%87.

As I mentioned before I don't have the setup to reproduce these issues and write a Guide for Windows users, but I can point to potential solutions when I see the errors, so it should be a joint effort of solving the issues and writing the guide. And for that it makes sense to have one common discussion thread instead of having separate issues for each problem that arises.
