### ISSUE TITLE
hello  :  train xiangqi   NNUE

### ISSUE THREAD

**Issue by byezilin** [ianfab/variant-nnue-pytorch#9]
很多拥有nvidia显卡的用户，不知道如何搭建NNUE权重训练环境，只懂得利用工具生成NNUE训练数据和验证数据。但是生成的数据存放在自己的硬盘上没有任何意义，请问你能否搭建一个公开的分布式训练网站，让全球的计算机算力都能集体参加到这个项目中来？
就如同国际象棋 http://training.lczero.org/  一样     希望也能搭建一个 xiangqi 的训练网站平台让广大在线用户共同参与训练，提升进步速度。 如果暂时训练网站不能马上建成，也请告诉 邮箱 地址或者  其他联络方式  能让普通用户把自己电脑生成的训练数据和验证数据压缩后 发送到你的手上 ，协助你训练。

**Comment by ianfab** [comment]
Having a distributed training would of course be great, but unfortunately I do not have the time to develop something like that.

Just out of curiosity, what is the main challenge in setting up the trainer? Is it the installation of CUDA, python, the python packages, or the compilation of the training data loader?

If people can access discord (via VPN), they can share links to their uploaded training data in the Fairy-Stockfish discord server. Otherwise you can also feel free to create a [discussion](https://github.com/ianfab/variant-nnue-pytorch/discussions) about Xiangqi NNUE training data in this repository, and then everyone can share their links there. I currently don't train networks due to lack of hardware, but others do, so they might pick up the training data from there then. That is why it shouldn't be a private communication like email, but somewhere public.

**Comment by byezilin** [comment]
其实是这样的，以我的计算机为例，windows 10  64位操作系统  ，nvidia 2080ti 显卡，cuda 10.1, cudnn-x64-v7.6.5.32,
在这样的条件下，如果我只是单纯的想要把 生成的训练数据training_data.bin和验证数据validation_data.bin，变成能够下棋使用的nnue文件，具体应该如何做？最好能够详细的告诉我：第一步该做什么，第二步该做什么，第三步该做什么？github上的教程有些太过专业很难理解。非常抱歉 我现在连python应该安装哪一种版本才算正确都不知道。后面还应该做些什么就更加艰难了。

**Comment by ianfab** [comment]
It would be best if people who get it to work (or at least part of it) extend the documentation at https://github.com/ianfab/variant-nnue-pytorch/wiki/%E4%B8%AD%E6%96%87. I tried to outline the steps there, but I can't fill in the detailed installation steps, since I neither have a Windows system nor a CUDA capable GPU, so it is impossible for me to test and reproduce the exact steps.
